# Generated by Django 3.2.7 on 2021-09-03 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='categora',
            new_name='categoria',
        ),
    ]
